version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nix-inputs:
        patterns:
          - "*"
        group-by: "dependency-name"
